############################# Chinese ############################
[zh-cn]
languageName = "中文"
title = "ICFC"
contentDir = "content/zh-cn" # content/zh-cn
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "@2021 icfc [苏ICP备19005908号-1](https://beian.miit.gov.cn)"


############################# English ############################
[en]
languageName = "En"
title = "Bigspring Hugo"
contentDir = "content/english" # content/english
weight = 2
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "@2021 icfc [苏ICP备19005908号-1](https://beian.miit.gov.cn)"
